### ISSUE TITLE
Missing font specifications :')

### ISSUE THREAD

**Issue by MissMadore** [MissMadore/working-with-jquery#1]
Hey @thomasjbradley the font specifications for this lesson were stated in the video but there's no mention of the specific attributes you used in the lesson or the README.md 

@mackenzierose told me I should tag you in an issue, so I did! 

Hurray Javascript :shipit:

**Comment by MacKenzieRose** [comment]
It's mostly for the animals like me that just read the assignment files and go 😬

**Comment by thomasjbradley** [comment]
I wonder what I meant because Markbot doesn‘t seem to be looking for anything font-specific.

**Comment by MacKenzieRose** [comment]
If this issue has been addressed, please make sure to close it 😄
